make cabal check happy
newer versions complain:

    $ cabal check
    The following errors are likely to affect your build negatively:
    Error: [git-protocol] Cloning over git:// might lead to an arbitrary code
    execution vulnerability. Furthermore, popular forges like GitHub do not
    support it. Use https:// or ssh:// instead.
    Error: Hackage would reject this package.
    make: *** [Makefile:71: check] Error 1

...which is not true in that hackage just accepted my upload of this very
package minutes ago. But let's make the checker happy.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>