fix some cabal warnings
xcffib.cabal:11:1: error:
cabal-version should be at the beginning of the file starting with spec version 2.2. See https://github.com/haskell/cabal/issues/4899

   10 | build-type:          Simple
   11 | cabal-version:       2.4
      | ^
Error: cabal: parse error

Warning: These warnings may cause trouble when distributing the package:
Warning: In 'extra-source-files': the pattern 'test/generator/*.py' does not
match the file 'test/generator/render_1.7.py' because the extensions do not
exactly match (e.g., foo.en.html does not exactly match *.html). To enable
looser suffix-only matching, set 'cabal-version: 2.4' or higher.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>