make: use twine to do pypi upload
Submitting dist/xcffib-0.12.0.tar.gz to https://upload.pypi.org/legacy/
Upload failed (400): Invalid value for blake2_256_digest. Error: Use a valid, hex-encoded, BLAKE2 message digest.
error: Upload failed (400): Invalid value for blake2_256_digest. Error: Use a valid, hex-encoded, BLAKE2 message digest.

https://github.com/pypa/distutils/issues/25
https://blog.ganssle.io/articles/2021/10/setup-py-deprecated.html#summary

I didn't switch sdist because it's new version from that blog post requires
a third party module... but maybe that'll break soon too.

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>