Revert "don't use __getattr__for Checked reasoning"
This reverts commit af2069b7536c3637f04bd328df07e02d90d78052.

This is causing failures in the qtile tests, for now, let's just revert and
re-release so we don't break things there:

    2025-09-27T01:08:05.0693956Z Traceback (most recent call last):
    2025-09-27T01:08:05.0694202Z   File "/home/runner/work/qtile/qtile/libqtile/backend/x11/core.py", line 358, in _xpoll
    2025-09-27T01:08:05.0694283Z     self.handle_event(event)
    2025-09-27T01:08:05.0694353Z     ~~~~~~~~~~~~~~~~~^^^^^^^
    2025-09-27T01:08:05.0694625Z   File "/home/runner/work/qtile/qtile/libqtile/backend/x11/core.py", line 325, in handle_event
    2025-09-27T01:08:05.0694702Z     ret = target(event)
    2025-09-27T01:08:05.0695010Z   File "/home/runner/work/qtile/qtile/libqtile/backend/x11/core.py", line 812, in handle_UnmapNotify
    2025-09-27T01:08:05.0695085Z     win.hide()
    2025-09-27T01:08:05.0695149Z     ~~~~~~~~^^
    2025-09-27T01:08:05.0695394Z   File "/home/runner/work/qtile/qtile/libqtile/backend/x11/window.py", line 760, in hide
    2025-09-27T01:08:05.0695472Z     self.window.unmap()
    2025-09-27T01:08:05.0695544Z     ~~~~~~~~~~~~~~~~~^^
    2025-09-27T01:08:05.0695786Z   File "/home/runner/work/qtile/qtile/libqtile/backend/x11/window.py", line 403, in unmap
    2025-09-27T01:08:05.0695916Z     self.conn.conn.core.UnmapWindowUnchecked(self.wid)
    2025-09-27T01:08:05.0695999Z     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    2025-09-27T01:08:05.0696421Z AttributeError: 'xprotoExtension' object has no attribute 'UnmapWindowUnchecked'. Did you mean: 'UnmapWindowChecked'?[0m

Signed-off-by: Tycho Andersen <tycho@tycho.pizza>